#!/bin/sh -l
JAVA=${JAVA_HOME:-/usr}/bin/java
exec "$JAVA" \
  -XX:+UseParallelGC \
  -XX:GCTimeRatio=4 \
  -XX:AdaptiveSizePolicyWeight=90 \
  -Xlog:gc:/var/log/decommission/gc.log \
  -Dcom.sun.management.jmxremote \
  -Dcom.sun.management.jmxremote.port=18089 \
  -Dcom.sun.management.jmxremote.local.only=false \
  -Dcom.sun.management.jmxremote.authenticate=false \
  -Dcom.sun.management.jmxremote.ssl=false \
  -Dlogging.config=/opt/decommission-tool/logback.xml \
  -Dlogback.configurationFile=/opt/decommission-tool/logback.xml \
  -jar \
  /opt/decommission-tool/decommission-tool.jar
