#!/bin/sh

adduser \
  --quiet \
  --system \
  --home /opt/decommission-tool \
  --no-create-home \
  --shell /bin/bash \
  --group \
  --gecos "MyGov Site Decommissioning Tool" \
  decommission

systemctl daemon-reload
systemctl enable decommission
systemctl start decommission
