#!/bin/sh

adduser \
  --quiet \
  --system \
  --home /opt/decommission-tool \
  --no-create-home \
  --shell /bin/bash \
  --group \
  --gecos "MyGov Site Decommissioning Tool" \
  decommission

mkdir -p /var/log/decommission-tool
chmod 755 /var/log/decommission-tool
chown decommission:nogroup /var/log/decommission-tool

if [ -x /bin/systemctl ]
then
    systemctl daemon-reload
    systemctl enable decommission
    systemctl start decommission
else
    service decommission start
fi
