application:
  name: decommission

logging:
  level:
    org.springframework.web: DEBUG
    org.mygovscot: DEBUG

server:
    port: 8089
    
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/decommission
    username: decommission
    password: decommission
    poolSize: 20
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: false
authentication:
    enabled: false
    endpoint: http://localhost:8086/security/
