application:
  name: decommission

logging:
  level:
    org.springframework: INFO
    org.mygovscot: INFO

server:
    port: 8089
    
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/decommission
    username: decommission
    password: decommission
    poolSize: 20
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: true

authentication:
    enabled: false
    endpoint: http://localhost:8086/security/
suggester:
    searchUrl: http://localhost:8082/direct/?size=5&q=