application:
  name: decommission

logging:
  level:
    org.springframework: INFO
    org.mygovscot: INFO

server:
    port: 8089

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost/decommission
    username: decommission
    password: decommission
    hikari:
      maximumPoolSize: 2

  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: none
    generate-ddl: false
  flyway:
    table: schema_version

