application:
  name: decommission-tool

logging:
  level:
    org.springframework.web: DEBUG
    org.mygovscot: INFO

server:
    port: 8089
    
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/decommission
    username: decommission
    password: decommission
    poolSize: 20
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: true
